WD = 'C:/Users/ucn/Education/20202/DSSGx/'
COUNTRY = 'Philippines'
COUNTRY_CODE = 'phl'
AVAILABLE_COUNTRIES = ['bra', 'tha'] # list of country names 
FEATURES = ['facebook']  # one or multiple of'population', 'facebook', 'opencell', 'satellite', 'speedtest'
SURVEY_AREAS = ''
SATELITTE_COLLECTIONS = {'CSP/HM/GlobalHumanModification': None, 'NOAA/VIIRS/DNB/MONTHLY_V1/VCMSLCFG': ['avg_rad', 'cf_cvg'], 'MODIS/006/MOD13A2': ['NDVI']}
SATELITTE_START_YEAR = 2014 # should be at least 2014
SATELITTE_END_YEAR = 2020 # 2021 might be exist for some collections..
SATELITTE_BUFFER = 5 # in kilometers
SATELITTE_MAX_CALL_SIZE = 5000 # default max call size
GOOGLE_SERVICES_ACCOUNT = 'xxxxxx@xxxxxxxx.iam.gserviceaccount.com'
GOOGLE_EARTH_ENGINE_API_JSON_KEY = 'xxxxxxx-xxxxxxxx.json'
OPENCELLID_ACCESS_TOKEN = '' # 2 calls per day
FACEBOOK_MARKETING_API_ACCESS_TOKEN = ''
FACEBOOK_AD_ACCOUNT_ID = ''
FACEBOOK_CALL_LIMIT = 300 # default fb ad_services call size
FACEBOOK_RADIUS = 5 # in kilometers
FACEBOOK_SCHOOL_DATA_LEN = {'bra': 11732, 'tha': 4723, 'phl': 4599}
SPEEDTEST_TILE_TYPE = 'mobile' # can be 'fixed' or 'mobile'
SPEEDTEST_TILE_YEAR = 2021 # data is available quarterly and usually approximately 1 month after quarter ends 
SPEEDTEST_TILE_QUARTER = 2 # 1-4 integer
POPULATION_DATASET_YEAR = 2020 # dataset currently available for years 2000-2020