model:
    loc: '/data/'
    file: 'training_sets/Brazil/training_set_v001.csv'
    population: 'worldpop/school_agg_pop_'
    school: 'school_loc/brazil_school_geolocation_master.csv'
    model_loc: '/model/'
    champion: '25_8_XGBoost.pkl'

features:
    target: ['target']
    predictors: ['avg_d_kbps', 'avg_u_kbps', 'mean_ghm', 'mean_avg_rad',
    'mean_cf_cvg', 'slope_year_avg_rad', 'slope_month_avg_rad', 'estimate_mau',
     'slope_month_cf_cvg', 'mean_NDVI', 'slope_year_NDVI', 'population']

country: 'Brazil'
country_3digit: 'bra'
country_pop: 212559409
