model:
    loc: '/files/data/training_sets/'
    file: 'Brazil/training_set_v001.csv'
    file: "thailand_dataset_v1_2.csv"
meta:
    experiment_name: "/Brazil/001"
    run_name: "Example Run Name Here"
    target: ['target']
    predictors: ['avg_d_kbps',
       'avg_u_kbps',
       'mean_ghm', 'mean_avg_rad', 'mean_cf_cvg',  'slope_year_avg_rad', 'slope_month_avg_rad', 'estimate_mau', 'slope_month_cf_cvg',
        'mean_NDVI', 'slope_year_NDVI', 'population']
    available_predictors: ['source_school_id', 'latitude', 'longitude', 'school_location',
       'geometry', 'target', 'mean_ghm', 'mean_avg_rad', 'change_year_avg_rad',
       'slope_year_avg_rad', 'change_month_avg_rad', 'slope_month_avg_rad',
       'mean_cf_cvg', 'change_year_cf_cvg', 'slope_year_cf_cvg',
       'change_month_cf_cvg', 'slope_month_cf_cvg', 'mean_NDVI',
       'change_year_NDVI', 'slope_year_NDVI', 'change_month_NDVI',
       'slope_month_NDVI', 'estimate_dau', 'estimate_mau', 'estimate_ready',
       'range', 'avg_d_kbps', 'avg_u_kbps', 'population']
parameter:
    test_size: .3
    inner_cv: 3
    iterations: 3
    threshold: .3
    Random_Forest:
        n_estimators: [4, 5, 6, 15]
        max_depth: [5, 10, 15, 20]
    lightgbm:
        boosting_type: ['dart']
        max_depth: [-1, 5, 10, 20]
        learning_rate: [0.01, 0.05, 0.1, 0.2]
        n_estimators: [50, 100, 200, 500]
    XGBoost:
          max_depth: [9, 12]
          eta: [ 0.15, 0.2]
          n_estimators: [350, 550]
